# Generated by Django 6.0.2 on 2026-03-02 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=200)),
                ('movieDescription', models.TextField()),
                ('releaseDate', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.CharField(max_length=10)),
                ('bookingStatus', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('reserved', 'Reserved')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('userReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingRecords', to=settings.AUTH_USER_MODEL)),
                ('movieReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingRecords', to='bookings.movie')),
                ('seatReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingRecords', to='bookings.seat')),
            ],
            options={
                'unique_together': {('movieReference', 'seatReference')},
            },
        ),
    ]
