# Generated by Django 6.0.2 on 2026-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='movie',
            new_name='bookMovie',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='bookSeats',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='bookTime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='bookUser',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='is_booked',
            new_name='seatBook',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='movie',
            new_name='seatMovie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieDuration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieRelease',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieTitle',
            field=models.CharField(default='', max_length=69),
        ),
        migrations.AddField(
            model_name='seat',
            name='seatNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
