# Generated by Django 6.0.2 on 2026-03-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_movie_poster_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
